import 'package:intl/date_symbols.dart';

const tiEthiopianDateSymbols = {
  "NAME": "ti",
  "ERAS": ["BC", "AD"],
  "ERANAMES": ["Before Christ", "Anno Domini"],
  "NARROWMONTHS": [
    "መ",
    "ጥ",
    "ሕ",
    "ታ",
    "ጥ",
    "የ",
    "መ",
    "ሚ",
    "ጉ",
    "ሰ",
    "ሓ",
    "ነ",
    "ጳ",
  ],
  "STANDALONENARROWMONTHS": [
    "መ",
    "ጥ",
    "ሕ",
    "ታ",
    "ጥ",
    "የ",
    "መ",
    "ሚ",
    "ጉ",
    "ሰ",
    "ሓ",
    "ነ",
    "ጳ",
  ],
  "MONTHS": [
    "መስከረም",
    "ጥቅምቲ",
    "ሕዳር",
    "ታሕሳስ",
    "ጥሪ",
    "የካቲት",
    "መጋቢት",
    "ሚያዝያ",
    "ጉንበት",
    "ሰነ",
    "ሓምለ",
    "ነሓሰ",
    "ጳጉሜን",
  ],
  "STANDALONEMONTHS": [
    "መስከረም",
    "ጥቅምቲ",
    "ሕዳር",
    "ታሕሳስ",
    "ጥሪ",
    "የካቲት",
    "መጋቢት",
    "ሚያዝያ",
    "ጉንበት",
    "ሰነ",
    "ሓምለ",
    "ነሓሰ",
    "ጳጉሜን",
  ],
  "SHORTMONTHS": [
    "መስከ",
    "ጥቅም",
    "ሕዳር",
    "ታሕሳ",
    "ጥሪ",
    "የካቲ",
    "መጋቢ",
    "ሚያዝ",
    "ጉንበ",
    "ሰነ",
    "ሓምለ",
    "ነሓሰ",
    "ጳጉሜ",
  ],
  "STANDALONESHORTMONTHS": [
    "መስከ",
    "ጥቅም",
    "ሕዳር",
    "ታሕሳ",
    "ጥሪ",
    "የካቲ",
    "መጋቢ",
    "ሚያዝ",
    "ጉንበ",
    "ሰነ",
    "ሓምለ",
    "ነሓሰ",
    "ጳጉሜ",
  ],
  "WEEKDAYS": [
    "ሰንበት",
    "ሶኒ",
    "ሰሉስ",
    "ረቡዕ",
    "ሓሙስ",
    "ዓርቢ",
    "ቀዳም",
  ],
  "STANDALONEWEEKDAYS": [
    "ሰንበት",
    "ሶኒ",
    "ሰሉስ",
    "ረቡዕ",
    "ሓሙስ",
    "ዓርቢ",
    "ቀዳም",
  ],
  "SHORTWEEKDAYS": [
    "ሰንበ",
    "ሶኒ",
    "ሰሉስ",
    "ረቡዕ",
    "ሓሙስ",
    "ዓርቢ",
    "ቀዳም",
  ],
  "STANDALONESHORTWEEKDAYS": [
    "ሰንበ",
    "ሶኒ",
    "ሰሉስ",
    "ረቡዕ",
    "ሓሙስ",
    "ዓርቢ",
    "ቀዳም",
  ],
  "NARROWWEEKDAYS": [
    "ሰ",
    "ሶ",
    "ሰ",
    "ረ",
    "ሓ",
    "ዓ",
    "ቀ",
  ],
  "STANDALONENARROWWEEKDAYS": [
    "ሰ",
    "ሶ",
    "ሰ",
    "ረ",
    "ሓ",
    "ዓ",
    "ቀ",
  ],
  "SHORTQUARTERS": ["Q1", "Q2", "Q3", "Q4"],
  "QUARTERS": ["1st quarter", "2nd quarter", "3rd quarter", "4th quarter"],
  "AMPMS": ["AM", "PM"],
  "DATEFORMATS": ["EEEE, MMMM d, y", "MMMM d, y", "MMM d, y", "M/d/yy"],
  "TIMEFORMATS": ["h:mm:ss a zzzz", "h:mm:ss a z", "h:mm:ss a", "h:mm a"],
  "AVAILABLEFORMATS": null,
  "FIRSTDAYOFWEEK": 6,
  "WEEKENDRANGE": [5, 6],
  "FIRSTWEEKCUTOFFDAY": 5,
  "DATETIMEFORMATS": ["{1} 'at' {0}", "{1} 'at' {0}", "{1}, {0}", "{1}, {0}"]
};

const amEthiopianDateSymbols = {
  "NAME": "am",
  "ERAS": ["BC", "AD"],
  "ERANAMES": ["Before Christ", "Anno Domini"],
  "NARROWMONTHS": [
    "መ",
    "ጥ",
    "ህ",
    "ታ",
    "ጥ",
    "የ",
    "መ",
    "ሚ",
    "ግ",
    "ሰ",
    "ሐ",
    "ነ",
    "ጳ",
  ],
  "STANDALONENARROWMONTHS": [
    "መ",
    "ጥ",
    "ህ",
    "ታ",
    "ጥ",
    "የ",
    "መ",
    "ሚ",
    "ግ",
    "ሰ",
    "ሐ",
    "ነ",
    "ጳ",
  ],
  "MONTHS": [
    "መስከረም",
    "ጥቅምት",
    "ሕዳር",
    "ታሕሣስ",
    "ጥር",
    "የካቲት",
    "መጋቢት",
    "ሚያዚያ",
    "ግንቦት",
    "ሰኔ",
    "ሐምሌ",
    "ነሐሴ",
    "ጳጉሜ"
  ],
  "STANDALONEMONTHS": [
    "መስከረም",
    "ጥቅምት",
    "ሕዳር",
    "ታሕሣስ",
    "ጥር",
    "የካቲት",
    "መጋቢት",
    "ሚያዚያ",
    "ግንቦት",
    "ሰኔ",
    "ሐምሌ",
    "ነሐሴ",
    "ጳጉሜ"
  ],
  "SHORTMONTHS": [
    "መስከ",
    "ጥቅም",
    "ሕዳር",
    "ታሕሣ",
    "ጥር",
    "የካቲ",
    "መጋቢ",
    "ሚያዚ",
    "ግንቦ",
    "ሰኔ",
    "ሐምሌ",
    "ነሐሴ",
    "ጳጉሜ"
  ],
  "STANDALONESHORTMONTHS": [
    "መስከ",
    "ጥቅም",
    "ሕዳር",
    "ታሕሣ",
    "ጥር",
    "የካቲ",
    "መጋቢ",
    "ሚያዚ",
    "ግንቦ",
    "ሰኔ",
    "ሐምሌ",
    "ነሐሴ",
    "ጳጉሜ"
  ],
  "WEEKDAYS": [
    "እሁድ",
    "ሰኞ",
    "ማክሰኞ",
    "ረቡዕ",
    "ሐሙስ",
    "ዓርብ",
    "ቅዳሜ",
  ],
  "STANDALONEWEEKDAYS": [
    "እሁድ",
    "ሰኞ",
    "ማክሰኞ",
    "ረቡዕ",
    "ሐሙስ",
    "ዓርብ",
    "ቅዳሜ",
  ],
  "SHORTWEEKDAYS": [
    "እሁድ",
    "ሰኞ",
    "ማክሰ",
    "ረቡዕ",
    "ሐሙስ",
    "ዓርብ",
    "ቅዳሜ",
  ],
  "STANDALONESHORTWEEKDAYS": [
    "እሁድ",
    "ሰኞ",
    "ማክሰ",
    "ረቡዕ",
    "ሐሙስ",
    "ዓርብ",
    "ቅዳሜ",
  ],
  "NARROWWEEKDAYS": [
    "እ",
    "ሰ",
    "ማ",
    "ረ",
    "ሐ",
    "ዓ",
    "ቅ",
  ],
  "STANDALONENARROWWEEKDAYS": [
    "እ",
    "ሰ",
    "ማ",
    "ረ",
    "ሐ",
    "ዓ",
    "ቅ",
  ],
  "SHORTQUARTERS": ["Q1", "Q2", "Q3", "Q4"],
  "QUARTERS": ["1st quarter", "2nd quarter", "3rd quarter", "4th quarter"],
  "AMPMS": ["AM", "PM"],
  "DATEFORMATS": ["EEEE, MMMM d, y", "MMMM d, y", "MMM d, y", "M/d/yy"],
  "TIMEFORMATS": ["h:mm:ss a zzzz", "h:mm:ss a z", "h:mm:ss a", "h:mm a"],
  "AVAILABLEFORMATS": null,
  "FIRSTDAYOFWEEK": 6,
  "WEEKENDRANGE": [5, 6],
  "FIRSTWEEKCUTOFFDAY": 5,
  "DATETIMEFORMATS": ["{1} 'at' {0}", "{1} 'at' {0}", "{1}, {0}", "{1}, {0}"]
};

const omEthiopianDateSymbols = {
  "NAME": "om",
  "ERAS": ["BC", "AD"],
  "ERANAMES": ["Before Christ", "Anno Domini"],
  "NARROWMONTHS": [
    "F",
    "I",
    "S",
    "M",
    "A",
    "G",
    "B",
    "E",
    "C",
    "W",
    "A",
    "H",
    "Q",
  ],
  "STANDALONENARROWMONTHS": [
    "F",
    "I",
    "S",
    "M",
    "A",
    "G",
    "B",
    "E",
    "C",
    "W",
    "A",
    "H",
    "Q",
  ],
  "MONTHS": [
    "Fulbaana",
    "Inkoloolessa",
    "Sadaasa",
    "Muddee",
    "Amajjii",
    "Guraandhala",
    "Bitootessa",
    "Ebla",
    "Caamsaa",
    "Waxabajjii",
    "Adoolessa",
    "Hagayya",
    "Qaammee",
  ],
  "STANDALONEMONTHS": [
    "Fulbaana",
    "Inkoloolessa",
    "Sadaasa",
    "Muddee",
    "Amajjii",
    "Guraandhala",
    "Bitootessa",
    "Ebla",
    "Caamsaa",
    "Waxabajjii",
    "Adoolessa",
    "Hagayya",
    "Qaammee",
  ],
  "SHORTMONTHS": [
    "Ful",
    "Ink",
    "Sad",
    "Mud",
    "Ama",
    "Gur",
    "Bit",
    "Ebl",
    "Caa",
    "Wax",
    "Ado",
    "Hag",
    "Qaa",
  ],
  "STANDALONESHORTMONTHS": [
    "Ful",
    "Ink",
    "Sad",
    "Mud",
    "Ama",
    "Gur",
    "Bit",
    "Ebl",
    "Caa",
    "Wax",
    "Ado",
    "Hag",
    "Qaa",
  ],
  "WEEKDAYS": [
    "Dilbata",
    "Wiixata",
    "Kibxata",
    "Roobii",
    "Kamisa",
    "Jimaata",
    "Sanbata",
  ],
  "STANDALONEWEEKDAYS": [
    "Dilbata",
    "Wiixata",
    "Kibxata",
    "Roobii",
    "Kamisa",
    "Jimaata",
    "Sanbata",
  ],
  "SHORTWEEKDAYS": [
    "Dil",
    "Wii",
    "Kib",
    "Roo",
    "Kam",
    "Jim",
    "San",
  ],
  "STANDALONESHORTWEEKDAYS": [
    "Dil",
    "Wii",
    "Kib",
    "Roo",
    "Kam",
    "Jim",
    "San",
  ],
  "NARROWWEEKDAYS": [
    "D",
    "W",
    "K",
    "R",
    "K",
    "J",
    "S",
  ],
  "STANDALONENARROWWEEKDAYS": [
    "D",
    "W",
    "K",
    "R",
    "K",
    "J",
    "S",
  ],
  "SHORTQUARTERS": ["Q1", "Q2", "Q3", "Q4"],
  "QUARTERS": ["1st quarter", "2nd quarter", "3rd quarter", "4th quarter"],
  "AMPMS": ["AM", "PM"],
  "DATEFORMATS": ["EEEE, MMMM d, y", "MMMM d, y", "MMM d, y", "M/d/yy"],
  "TIMEFORMATS": ["h:mm:ss a zzzz", "h:mm:ss a z", "h:mm:ss a", "h:mm a"],
  "AVAILABLEFORMATS": null,
  "FIRSTDAYOFWEEK": 6,
  "WEEKENDRANGE": [5, 6],
  "FIRSTWEEKCUTOFFDAY": 5,
  "DATETIMEFORMATS": ["{1} 'at' {0}", "{1} 'at' {0}", "{1}, {0}", "{1}, {0}"]
};

const soEthiopianDateSymbols = {
  "NAME": "so",
  "ERAS": ["BC", "AD"],
  "ERANAMES": ["Before Christ", "Anno Domini"],
  "NARROWMONTHS": [
    "S",
    "O",
    "N",
    "D",
    "J",
    "F",
    "M",
    "A",
    "L",
    "J",
    "J",
    "O",
    "P",
  ],
  "STANDALONENARROWMONTHS": [
    "S",
    "O",
    "N",
    "D",
    "J",
    "F",
    "M",
    "A",
    "L",
    "J",
    "J",
    "O",
    "P",
  ],
  "MONTHS": [
    "Sebtembar",
    "Oktoobar",
    "Nofeembar",
    "December",
    "Janaayo",
    "Febraayo",
    "Maarso",
    "Abriil",
    "Laga yaabaa",
    "Juun",
    "Julaay",
    "Ogosto",
    "Pagume",
  ],
  "STANDALONEMONTHS": [
    "Sebtembar",
    "Oktoobar",
    "Nofeembar",
    "December",
    "Janaayo",
    "Febraayo",
    "Maarso",
    "Abriil",
    "Laga yaabaa",
    "Juun",
    "Julaay",
    "Ogosto",
    "Pagume",
  ],
  "SHORTMONTHS": [
    "Seb",
    "Okt",
    "Nof",
    "Dec",
    "Jan",
    "Feb",
    "Maa",
    "Abr",
    "Lag",
    "Juu",
    "Jul",
    "Ogo",
    "Pag",
  ],
  "STANDALONESHORTMONTHS": [
    "Seb",
    "Okt",
    "Nof",
    "Dec",
    "Jan",
    "Feb",
    "Maa",
    "Abr",
    "Lag",
    "Juu",
    "Jul",
    "Ogo",
    "Pag",
  ],
  "WEEKDAYS": [
    "Axad",
    "Isniin",
    "Talaado",
    "Arbacada",
    "Khamiis",
    "Jimcaha",
    "Sabti",
  ],
  "STANDALONEWEEKDAYS": [
    "Axad",
    "Isniin",
    "Talaado",
    "Arbacada",
    "Khamiis",
    "Jimcaha",
    "Sabti",
  ],
  "SHORTWEEKDAYS": [
    "Axa",
    "Isn",
    "Tal",
    "Arb",
    "Kha",
    "Jim",
    "Sab",
  ],
  "STANDALONESHORTWEEKDAYS": [
    "Axa",
    "Isn",
    "Tal",
    "Arb",
    "Kha",
    "Jim",
    "Sab",
  ],
  "NARROWWEEKDAYS": [
    "A",
    "I",
    "T",
    "A",
    "K",
    "J",
    "S",
  ],
  "STANDALONENARROWWEEKDAYS": [
    "A",
    "I",
    "T",
    "A",
    "K",
    "J",
    "S",
  ],
  "SHORTQUARTERS": ["Q1", "Q2", "Q3", "Q4"],
  "QUARTERS": ["1st quarter", "2nd quarter", "3rd quarter", "4th quarter"],
  "AMPMS": ["AM", "PM"],
  "DATEFORMATS": ["EEEE, MMMM d, y", "MMMM d, y", "MMM d, y", "M/d/yy"],
  "TIMEFORMATS": ["h:mm:ss a zzzz", "h:mm:ss a z", "h:mm:ss a", "h:mm a"],
  "AVAILABLEFORMATS": null,
  "FIRSTDAYOFWEEK": 6,
  "WEEKENDRANGE": [5, 6],
  "FIRSTWEEKCUTOFFDAY": 5,
  "DATETIMEFORMATS": ["{1} 'at' {0}", "{1} 'at' {0}", "{1}, {0}", "{1}, {0}"]
};

class EthiopianDateSymbol {
  final String locale;
  late DateSymbols dateSymbols;

  EthiopianDateSymbol(this.locale) {
    switch (locale.toLowerCase()) {
      case "am":
        dateSymbols = DateSymbols.deserializeFromMap(amEthiopianDateSymbols);
        break;
      case "ti":
        dateSymbols = DateSymbols.deserializeFromMap(tiEthiopianDateSymbols);
        break;
      case "so":
        dateSymbols = DateSymbols.deserializeFromMap(soEthiopianDateSymbols);
        break;
      case "om":
        dateSymbols = DateSymbols.deserializeFromMap(omEthiopianDateSymbols);
        break;
      default:
        dateSymbols = DateSymbols.deserializeFromMap(omEthiopianDateSymbols);
        break;
    }
  }
}
